#!/usr/bin/env bash

searchEngine=$(cat $HOME/Scripts/search.txt | awk '{print $1}' | dmenu $@ -p "Search Engine:")
url=$(cat $HOME/Scripts/search.txt | grep "^$searchEngine " | awk '{print $2}' | head -n 1)

if [ "$searchEngine" != "" ]; then
    searchTerm=$(: | dmenu $@ -i -l 0 -p "$searchEngine:")
    searchTerm=${searchTerm//+/%2B}
    searchTerm=${searchTerm//&/%26}
fi
if [ "$searchTerm" != "" ]; then
    xdg-open "$url$searchTerm"
fi
